#!/usr/bin/env bash
/nix/store/q2gm8j153ywipq98wasmhjnscmc015zr-pnpm-10.19.0/bin/pnpm "$@"
if [[ "$1" == "install" ]] || [[ "$1" == "i" ]] || [[ "$1" == "add" ]]; then
  for workerd in node_modules/.pnpm/@cloudflare+workerd-linux-64@*/node_modules/@cloudflare/workerd-linux-64/bin/workerd; do
    if [ -f "$workerd" ]; then
      echo "Patching $workerd..."
      /nix/store/85n78yrssyfc65f32yxpqqcpzkgbjv8c-patchelf-0.15.2/bin/patchelf --set-interpreter "$(cat /nix/store/x8mydcgbry214s802nzvy7fdljx404ym-gcc-wrapper-14.3.0/nix-support/dynamic-linker)" "$workerd"
      /nix/store/85n78yrssyfc65f32yxpqqcpzkgbjv8c-patchelf-0.15.2/bin/patchelf --set-rpath "/nix/store/z7a34j3xnp66rpddayyxrxwsahxccbip-gcc-14.3.0-lib/lib:/nix/store/llswcygvgv9x2sa3z6j7i0g5iqqmn5gn-openssl-3.6.0/lib:/nix/store/z55x0q74zldi64iwamqf8wgrm2iza5rk-zlib-1.3.1/lib" "$workerd"
    fi
  done
fi
